name: Deploy to neociteis

on:
  push:
    branches:
      - main

env:
  node-version: lts/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
    - run: npm i
    - run: npm run build
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: false
